### ISSUE TITLE
Feat: 상태 및 조건에 따른 todo 정렬, 필터링

### ISSUE THREAD

**Issue by hwb0218** [FOB-7avaScript/Assignment8-JK-YH-WB-SH#5]
### **예상시간**
6시간

---

### **하위 태스크**
- [x]  조건에 따른 todo 정렬
- [x]  상태에 따른 sorted state 변경
- [x]  useTodo API 호출
